1_Task
js-tasks-ru/jsbasic-20230428_sergey-khatyukhin pull request #2
Opened 2023-05-03 11:50 UTC by SergeyKhatyukhin

2023-05-03 11:50 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-03 13:54 UTC, SinimaWath requested changes

2023-05-03 13:54 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  if (typeof name === "string") {if (name.length < 4 || name === '' || name.includes(' ')) {return false;} else {return true;}} else {return false;}
Получилось сложное решение, давай упростим используя операторы &&, ||:
`return typeof name === "string" && ... && ... && ... ;`

2023-05-03 13:54 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  return Big + end;}
Давай поправим выравнивание:
```
if (str === '') {
  return '';
} else {
     Big = str[0].toUpperCase();
    end = str.substring(1);
     return Big + end;
}
```

https://learn.javascript.ru/coding-style

2023-05-03 13:54 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  LC=str.toLowerCase();
LC - это у тебя не переменная, нужно использовать let/const

2023-05-03 13:54 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  if (LC.indexOf('xxx')>=0 || LC.indexOf('1xbet')>=0) {return true;} else {return false;}
`return LC.indexOf('xxx')>=0 || LC.indexOf('1xbet')>=0`, так как результат операции и так boolean

2023-05-03 13:54 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  if (str.length <= maxlength) {return str;} else {return str.substr(0, maxlength-1) + "…"}
Однострочники не предпочтительны

https://learn.javascript.ru/coding-style

2023-05-03 14:49 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-04 09:16 UTC, SinimaWath requested changes

2023-05-04 09:16 UTC, SinimaWath commented on 1-module/3-task/index.js
> +    Big = str[0].toUpperCase();
Это не переменная, нужно добавить let/const

2023-05-04 09:16 UTC, SinimaWath commented on 1-module/3-task/index.js
> +    end = str.substring(1);
Это не переменная, нужно добавить let/const

2023-05-04 10:19 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-05 10:15 UTC, SinimaWath approved these changes

2023-05-05 10:16 UTC, merged